name: Build and Push Docker Image CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - "**/README.md"
  schedule:
    - cron: "30 0 * * 0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: checkout repo
        uses: actions/checkout@v3

      - name: set image tag
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            burningc4/ubi-code
          tags: |
            type=raw,value={{sha}}
            type=raw,latest
            type=raw,value={{date 'YYYYWW'}}

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
